services:
  nginx: ## Cloudfrontの代わり
    image: nginx:latest
    ports:
      - 80:80
    expose:
      - "80"
    volumes:
      - ./local/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - internal

  backend:
    build:
      context: ./backend
    expose:
      - "8000"
    networks:
      - internal

networks:
  internal:
    driver: bridge